`timescale 1ns/1ps
// Auto-generated by autombist. Port-only model of the memory for SYNTHESIS
// ONLY -- read it with `read_verilog -lib` so the memory instance survives
// flatten as a test boundary. Not a simulation model.
(* blackbox *)
module input_demo_8x16_scn4m #(
    parameter integer ADDR_WIDTH = 4,
    parameter integer DATA_WIDTH = 8,
    parameter integer NUM_SPARE_ROWS = 0,
    parameter integer NUM_SPARE_COLS = 0
) (
    input  wire clk0,
    input  wire csb0,
    input  wire web0,
    input  wire [3:0] addr0,
    input  wire [7:0] din0,
    output wire [7:0] dout0
);
endmodule
