`timescale 1ns/1ps
// Self-checking MBIST testbench for input_demo_8x16_scn4m_mbist -- generated by autombist.
//
// Runs the built-in self-test from the wrapper's own pins: reset with
// test_mode=1, set bist_start=1 and hold it (the controller keeps its result
// only while start stays high, just as a JTAG data-register write holds it),
// wait for bist_done, then check bist_fail. Prints one "MBIST RESULT:" line
// with the test's length in clk cycles, and ends with $fatal -- a non-zero exit
// from the simulator -- on a failure or a timeout. run_tb.sh compiles it with
// the generated RTL and the memory's own simulation model.
//
// Timeout: 420 clk cycles, autombist's bound on this
// configuration's BIST length; override with -DMBIST_MAX_CYCLES=<n>.
`ifndef MBIST_MAX_CYCLES
`define MBIST_MAX_CYCLES 420
`endif

module tb_input_demo_8x16_scn4m_mbist;
    localparam integer ADDR_WIDTH = 4;
    localparam integer DATA_WIDTH = 8;

    logic clk        = 1'b0;
    logic rst_n      = 1'b0;
    logic test_mode  = 1'b1;
    logic bist_start = 1'b0;
    wire  bist_done;
    wire  bist_fail;
    logic func_csb = '1;
    logic [ADDR_WIDTH-1:0] func_addr = '0;
    logic [DATA_WIDTH-1:0] func_din = '0;
    logic func_we = '0;
    wire  [DATA_WIDTH-1:0] func_dout;

    input_demo_8x16_scn4m_mbist dut (
        .clk(clk),
        .rst_n(rst_n),
        .test_mode(test_mode),
        .bist_start(bist_start),
        .bist_done(bist_done),
        .bist_fail(bist_fail),
        .func_csb(func_csb),
        .func_addr(func_addr),
        .func_din(func_din),
        .func_we(func_we),
        .func_dout(func_dout)
    );

    always #5 clk = ~clk;

    integer cycles;
    initial begin
        repeat (4) @(negedge clk);
        rst_n = 1'b1;
        repeat (2) @(negedge clk);
        bist_start = 1'b1;
        cycles = 0;
        while (bist_done !== 1'b1 && cycles < `MBIST_MAX_CYCLES) begin
            @(negedge clk);
            cycles = cycles + 1;
        end
        if (bist_done !== 1'b1)
            $fatal(1, "MBIST RESULT: TIMEOUT -- bist_done not set after %0d clk cycles", cycles);
        if (bist_fail !== 1'b0)
            $fatal(1, "MBIST RESULT: FAIL -- bist_fail=%b after %0d clk cycles", bist_fail, cycles);
        $display("MBIST RESULT: PASS -- %0d clk cycles", cycles);
        $finish;
    end
endmodule
