// soc4_glue.v -- SoC4 (DSP Trio) interconnect stub for assemble_soc().
// AUTO-GENERATED (gen_soc4_glue.py) from the frozen iiravg/boxcar/
// genericfir_small scan+wrap JSON. Pure dataflow pipeline, no glue-level
// state at all (unlike SoC1-3, nothing here needed blackboxing).
`default_nettype none

module soc4_glue (
	input  wire         i_clk,
	input  wire         i_reset,
	input  wire         i_ce,

	input  wire [14:0]  i_sample,
	input  wire [5:0]   i_navg,
	input  wire         i_tap_wr,
	input  wire [7:0]   i_tap,
	output wire [22:0]  o_result,

	input  wire soc_wbr_se,
	input  wire soc_wbr_si,
	output wire soc_wbr_so
);

	wire [15:0] iir_out;
	wire [21:0] boxcar_out;
	wire wbr_mid1, wbr_mid2;

	wire n_iir_scan_en;
	wire n_iir_scan_in_0;
	wire n_iir_scan_in_1;
	wire n_iir_scan_out_0;
	wire n_iir_scan_out_1;

	iiravg u_iiravg (
		.i_ce (i_ce),
		.i_clk (i_clk),
		.i_data (i_sample),
		.i_reset (i_reset),
		.o_data (iir_out),
		.scan_en (n_iir_scan_en),
		.scan_in_0 (n_iir_scan_in_0),
		.scan_in_1 (n_iir_scan_in_1),
		.scan_out_0 (n_iir_scan_out_0),
		.scan_out_1 (n_iir_scan_out_1),
		.wbr_se (soc_wbr_se),
		.wbr_si (soc_wbr_si),
		.wbr_so (wbr_mid1)
	);

	wire n_box_scan_en;
	wire n_box_scan_in_0;
	wire n_box_scan_in_1;
	wire n_box_scan_in_10;
	wire n_box_scan_in_100;
	wire n_box_scan_in_101;
	wire n_box_scan_in_102;
	wire n_box_scan_in_103;
	wire n_box_scan_in_104;
	wire n_box_scan_in_105;
	wire n_box_scan_in_106;
	wire n_box_scan_in_107;
	wire n_box_scan_in_108;
	wire n_box_scan_in_109;
	wire n_box_scan_in_11;
	wire n_box_scan_in_110;
	wire n_box_scan_in_111;
	wire n_box_scan_in_112;
	wire n_box_scan_in_12;
	wire n_box_scan_in_13;
	wire n_box_scan_in_14;
	wire n_box_scan_in_15;
	wire n_box_scan_in_16;
	wire n_box_scan_in_17;
	wire n_box_scan_in_18;
	wire n_box_scan_in_19;
	wire n_box_scan_in_2;
	wire n_box_scan_in_20;
	wire n_box_scan_in_21;
	wire n_box_scan_in_22;
	wire n_box_scan_in_23;
	wire n_box_scan_in_24;
	wire n_box_scan_in_25;
	wire n_box_scan_in_26;
	wire n_box_scan_in_27;
	wire n_box_scan_in_28;
	wire n_box_scan_in_29;
	wire n_box_scan_in_3;
	wire n_box_scan_in_30;
	wire n_box_scan_in_31;
	wire n_box_scan_in_32;
	wire n_box_scan_in_33;
	wire n_box_scan_in_34;
	wire n_box_scan_in_35;
	wire n_box_scan_in_36;
	wire n_box_scan_in_37;
	wire n_box_scan_in_38;
	wire n_box_scan_in_39;
	wire n_box_scan_in_4;
	wire n_box_scan_in_40;
	wire n_box_scan_in_41;
	wire n_box_scan_in_42;
	wire n_box_scan_in_43;
	wire n_box_scan_in_44;
	wire n_box_scan_in_45;
	wire n_box_scan_in_46;
	wire n_box_scan_in_47;
	wire n_box_scan_in_48;
	wire n_box_scan_in_49;
	wire n_box_scan_in_5;
	wire n_box_scan_in_50;
	wire n_box_scan_in_51;
	wire n_box_scan_in_52;
	wire n_box_scan_in_53;
	wire n_box_scan_in_54;
	wire n_box_scan_in_55;
	wire n_box_scan_in_56;
	wire n_box_scan_in_57;
	wire n_box_scan_in_58;
	wire n_box_scan_in_59;
	wire n_box_scan_in_6;
	wire n_box_scan_in_60;
	wire n_box_scan_in_61;
	wire n_box_scan_in_62;
	wire n_box_scan_in_63;
	wire n_box_scan_in_64;
	wire n_box_scan_in_65;
	wire n_box_scan_in_66;
	wire n_box_scan_in_67;
	wire n_box_scan_in_68;
	wire n_box_scan_in_69;
	wire n_box_scan_in_7;
	wire n_box_scan_in_70;
	wire n_box_scan_in_71;
	wire n_box_scan_in_72;
	wire n_box_scan_in_73;
	wire n_box_scan_in_74;
	wire n_box_scan_in_75;
	wire n_box_scan_in_76;
	wire n_box_scan_in_77;
	wire n_box_scan_in_78;
	wire n_box_scan_in_79;
	wire n_box_scan_in_8;
	wire n_box_scan_in_80;
	wire n_box_scan_in_81;
	wire n_box_scan_in_82;
	wire n_box_scan_in_83;
	wire n_box_scan_in_84;
	wire n_box_scan_in_85;
	wire n_box_scan_in_86;
	wire n_box_scan_in_87;
	wire n_box_scan_in_88;
	wire n_box_scan_in_89;
	wire n_box_scan_in_9;
	wire n_box_scan_in_90;
	wire n_box_scan_in_91;
	wire n_box_scan_in_92;
	wire n_box_scan_in_93;
	wire n_box_scan_in_94;
	wire n_box_scan_in_95;
	wire n_box_scan_in_96;
	wire n_box_scan_in_97;
	wire n_box_scan_in_98;
	wire n_box_scan_in_99;
	wire n_box_scan_out_0;
	wire n_box_scan_out_1;
	wire n_box_scan_out_10;
	wire n_box_scan_out_100;
	wire n_box_scan_out_101;
	wire n_box_scan_out_102;
	wire n_box_scan_out_103;
	wire n_box_scan_out_104;
	wire n_box_scan_out_105;
	wire n_box_scan_out_106;
	wire n_box_scan_out_107;
	wire n_box_scan_out_108;
	wire n_box_scan_out_109;
	wire n_box_scan_out_11;
	wire n_box_scan_out_110;
	wire n_box_scan_out_111;
	wire n_box_scan_out_112;
	wire n_box_scan_out_12;
	wire n_box_scan_out_13;
	wire n_box_scan_out_14;
	wire n_box_scan_out_15;
	wire n_box_scan_out_16;
	wire n_box_scan_out_17;
	wire n_box_scan_out_18;
	wire n_box_scan_out_19;
	wire n_box_scan_out_2;
	wire n_box_scan_out_20;
	wire n_box_scan_out_21;
	wire n_box_scan_out_22;
	wire n_box_scan_out_23;
	wire n_box_scan_out_24;
	wire n_box_scan_out_25;
	wire n_box_scan_out_26;
	wire n_box_scan_out_27;
	wire n_box_scan_out_28;
	wire n_box_scan_out_29;
	wire n_box_scan_out_3;
	wire n_box_scan_out_30;
	wire n_box_scan_out_31;
	wire n_box_scan_out_32;
	wire n_box_scan_out_33;
	wire n_box_scan_out_34;
	wire n_box_scan_out_35;
	wire n_box_scan_out_36;
	wire n_box_scan_out_37;
	wire n_box_scan_out_38;
	wire n_box_scan_out_39;
	wire n_box_scan_out_4;
	wire n_box_scan_out_40;
	wire n_box_scan_out_41;
	wire n_box_scan_out_42;
	wire n_box_scan_out_43;
	wire n_box_scan_out_44;
	wire n_box_scan_out_45;
	wire n_box_scan_out_46;
	wire n_box_scan_out_47;
	wire n_box_scan_out_48;
	wire n_box_scan_out_49;
	wire n_box_scan_out_5;
	wire n_box_scan_out_50;
	wire n_box_scan_out_51;
	wire n_box_scan_out_52;
	wire n_box_scan_out_53;
	wire n_box_scan_out_54;
	wire n_box_scan_out_55;
	wire n_box_scan_out_56;
	wire n_box_scan_out_57;
	wire n_box_scan_out_58;
	wire n_box_scan_out_59;
	wire n_box_scan_out_6;
	wire n_box_scan_out_60;
	wire n_box_scan_out_61;
	wire n_box_scan_out_62;
	wire n_box_scan_out_63;
	wire n_box_scan_out_64;
	wire n_box_scan_out_65;
	wire n_box_scan_out_66;
	wire n_box_scan_out_67;
	wire n_box_scan_out_68;
	wire n_box_scan_out_69;
	wire n_box_scan_out_7;
	wire n_box_scan_out_70;
	wire n_box_scan_out_71;
	wire n_box_scan_out_72;
	wire n_box_scan_out_73;
	wire n_box_scan_out_74;
	wire n_box_scan_out_75;
	wire n_box_scan_out_76;
	wire n_box_scan_out_77;
	wire n_box_scan_out_78;
	wire n_box_scan_out_79;
	wire n_box_scan_out_8;
	wire n_box_scan_out_80;
	wire n_box_scan_out_81;
	wire n_box_scan_out_82;
	wire n_box_scan_out_83;
	wire n_box_scan_out_84;
	wire n_box_scan_out_85;
	wire n_box_scan_out_86;
	wire n_box_scan_out_87;
	wire n_box_scan_out_88;
	wire n_box_scan_out_89;
	wire n_box_scan_out_9;
	wire n_box_scan_out_90;
	wire n_box_scan_out_91;
	wire n_box_scan_out_92;
	wire n_box_scan_out_93;
	wire n_box_scan_out_94;
	wire n_box_scan_out_95;
	wire n_box_scan_out_96;
	wire n_box_scan_out_97;
	wire n_box_scan_out_98;
	wire n_box_scan_out_99;

	boxcar u_boxcar (
		.i_ce (i_ce),
		.i_clk (i_clk),
		.i_navg (i_navg),
		.i_reset (i_reset),
		.i_sample (iir_out),
		.o_result (boxcar_out),
		.scan_en (n_box_scan_en),
		.scan_in_0 (n_box_scan_in_0),
		.scan_in_1 (n_box_scan_in_1),
		.scan_in_10 (n_box_scan_in_10),
		.scan_in_100 (n_box_scan_in_100),
		.scan_in_101 (n_box_scan_in_101),
		.scan_in_102 (n_box_scan_in_102),
		.scan_in_103 (n_box_scan_in_103),
		.scan_in_104 (n_box_scan_in_104),
		.scan_in_105 (n_box_scan_in_105),
		.scan_in_106 (n_box_scan_in_106),
		.scan_in_107 (n_box_scan_in_107),
		.scan_in_108 (n_box_scan_in_108),
		.scan_in_109 (n_box_scan_in_109),
		.scan_in_11 (n_box_scan_in_11),
		.scan_in_110 (n_box_scan_in_110),
		.scan_in_111 (n_box_scan_in_111),
		.scan_in_112 (n_box_scan_in_112),
		.scan_in_12 (n_box_scan_in_12),
		.scan_in_13 (n_box_scan_in_13),
		.scan_in_14 (n_box_scan_in_14),
		.scan_in_15 (n_box_scan_in_15),
		.scan_in_16 (n_box_scan_in_16),
		.scan_in_17 (n_box_scan_in_17),
		.scan_in_18 (n_box_scan_in_18),
		.scan_in_19 (n_box_scan_in_19),
		.scan_in_2 (n_box_scan_in_2),
		.scan_in_20 (n_box_scan_in_20),
		.scan_in_21 (n_box_scan_in_21),
		.scan_in_22 (n_box_scan_in_22),
		.scan_in_23 (n_box_scan_in_23),
		.scan_in_24 (n_box_scan_in_24),
		.scan_in_25 (n_box_scan_in_25),
		.scan_in_26 (n_box_scan_in_26),
		.scan_in_27 (n_box_scan_in_27),
		.scan_in_28 (n_box_scan_in_28),
		.scan_in_29 (n_box_scan_in_29),
		.scan_in_3 (n_box_scan_in_3),
		.scan_in_30 (n_box_scan_in_30),
		.scan_in_31 (n_box_scan_in_31),
		.scan_in_32 (n_box_scan_in_32),
		.scan_in_33 (n_box_scan_in_33),
		.scan_in_34 (n_box_scan_in_34),
		.scan_in_35 (n_box_scan_in_35),
		.scan_in_36 (n_box_scan_in_36),
		.scan_in_37 (n_box_scan_in_37),
		.scan_in_38 (n_box_scan_in_38),
		.scan_in_39 (n_box_scan_in_39),
		.scan_in_4 (n_box_scan_in_4),
		.scan_in_40 (n_box_scan_in_40),
		.scan_in_41 (n_box_scan_in_41),
		.scan_in_42 (n_box_scan_in_42),
		.scan_in_43 (n_box_scan_in_43),
		.scan_in_44 (n_box_scan_in_44),
		.scan_in_45 (n_box_scan_in_45),
		.scan_in_46 (n_box_scan_in_46),
		.scan_in_47 (n_box_scan_in_47),
		.scan_in_48 (n_box_scan_in_48),
		.scan_in_49 (n_box_scan_in_49),
		.scan_in_5 (n_box_scan_in_5),
		.scan_in_50 (n_box_scan_in_50),
		.scan_in_51 (n_box_scan_in_51),
		.scan_in_52 (n_box_scan_in_52),
		.scan_in_53 (n_box_scan_in_53),
		.scan_in_54 (n_box_scan_in_54),
		.scan_in_55 (n_box_scan_in_55),
		.scan_in_56 (n_box_scan_in_56),
		.scan_in_57 (n_box_scan_in_57),
		.scan_in_58 (n_box_scan_in_58),
		.scan_in_59 (n_box_scan_in_59),
		.scan_in_6 (n_box_scan_in_6),
		.scan_in_60 (n_box_scan_in_60),
		.scan_in_61 (n_box_scan_in_61),
		.scan_in_62 (n_box_scan_in_62),
		.scan_in_63 (n_box_scan_in_63),
		.scan_in_64 (n_box_scan_in_64),
		.scan_in_65 (n_box_scan_in_65),
		.scan_in_66 (n_box_scan_in_66),
		.scan_in_67 (n_box_scan_in_67),
		.scan_in_68 (n_box_scan_in_68),
		.scan_in_69 (n_box_scan_in_69),
		.scan_in_7 (n_box_scan_in_7),
		.scan_in_70 (n_box_scan_in_70),
		.scan_in_71 (n_box_scan_in_71),
		.scan_in_72 (n_box_scan_in_72),
		.scan_in_73 (n_box_scan_in_73),
		.scan_in_74 (n_box_scan_in_74),
		.scan_in_75 (n_box_scan_in_75),
		.scan_in_76 (n_box_scan_in_76),
		.scan_in_77 (n_box_scan_in_77),
		.scan_in_78 (n_box_scan_in_78),
		.scan_in_79 (n_box_scan_in_79),
		.scan_in_8 (n_box_scan_in_8),
		.scan_in_80 (n_box_scan_in_80),
		.scan_in_81 (n_box_scan_in_81),
		.scan_in_82 (n_box_scan_in_82),
		.scan_in_83 (n_box_scan_in_83),
		.scan_in_84 (n_box_scan_in_84),
		.scan_in_85 (n_box_scan_in_85),
		.scan_in_86 (n_box_scan_in_86),
		.scan_in_87 (n_box_scan_in_87),
		.scan_in_88 (n_box_scan_in_88),
		.scan_in_89 (n_box_scan_in_89),
		.scan_in_9 (n_box_scan_in_9),
		.scan_in_90 (n_box_scan_in_90),
		.scan_in_91 (n_box_scan_in_91),
		.scan_in_92 (n_box_scan_in_92),
		.scan_in_93 (n_box_scan_in_93),
		.scan_in_94 (n_box_scan_in_94),
		.scan_in_95 (n_box_scan_in_95),
		.scan_in_96 (n_box_scan_in_96),
		.scan_in_97 (n_box_scan_in_97),
		.scan_in_98 (n_box_scan_in_98),
		.scan_in_99 (n_box_scan_in_99),
		.scan_out_0 (n_box_scan_out_0),
		.scan_out_1 (n_box_scan_out_1),
		.scan_out_10 (n_box_scan_out_10),
		.scan_out_100 (n_box_scan_out_100),
		.scan_out_101 (n_box_scan_out_101),
		.scan_out_102 (n_box_scan_out_102),
		.scan_out_103 (n_box_scan_out_103),
		.scan_out_104 (n_box_scan_out_104),
		.scan_out_105 (n_box_scan_out_105),
		.scan_out_106 (n_box_scan_out_106),
		.scan_out_107 (n_box_scan_out_107),
		.scan_out_108 (n_box_scan_out_108),
		.scan_out_109 (n_box_scan_out_109),
		.scan_out_11 (n_box_scan_out_11),
		.scan_out_110 (n_box_scan_out_110),
		.scan_out_111 (n_box_scan_out_111),
		.scan_out_112 (n_box_scan_out_112),
		.scan_out_12 (n_box_scan_out_12),
		.scan_out_13 (n_box_scan_out_13),
		.scan_out_14 (n_box_scan_out_14),
		.scan_out_15 (n_box_scan_out_15),
		.scan_out_16 (n_box_scan_out_16),
		.scan_out_17 (n_box_scan_out_17),
		.scan_out_18 (n_box_scan_out_18),
		.scan_out_19 (n_box_scan_out_19),
		.scan_out_2 (n_box_scan_out_2),
		.scan_out_20 (n_box_scan_out_20),
		.scan_out_21 (n_box_scan_out_21),
		.scan_out_22 (n_box_scan_out_22),
		.scan_out_23 (n_box_scan_out_23),
		.scan_out_24 (n_box_scan_out_24),
		.scan_out_25 (n_box_scan_out_25),
		.scan_out_26 (n_box_scan_out_26),
		.scan_out_27 (n_box_scan_out_27),
		.scan_out_28 (n_box_scan_out_28),
		.scan_out_29 (n_box_scan_out_29),
		.scan_out_3 (n_box_scan_out_3),
		.scan_out_30 (n_box_scan_out_30),
		.scan_out_31 (n_box_scan_out_31),
		.scan_out_32 (n_box_scan_out_32),
		.scan_out_33 (n_box_scan_out_33),
		.scan_out_34 (n_box_scan_out_34),
		.scan_out_35 (n_box_scan_out_35),
		.scan_out_36 (n_box_scan_out_36),
		.scan_out_37 (n_box_scan_out_37),
		.scan_out_38 (n_box_scan_out_38),
		.scan_out_39 (n_box_scan_out_39),
		.scan_out_4 (n_box_scan_out_4),
		.scan_out_40 (n_box_scan_out_40),
		.scan_out_41 (n_box_scan_out_41),
		.scan_out_42 (n_box_scan_out_42),
		.scan_out_43 (n_box_scan_out_43),
		.scan_out_44 (n_box_scan_out_44),
		.scan_out_45 (n_box_scan_out_45),
		.scan_out_46 (n_box_scan_out_46),
		.scan_out_47 (n_box_scan_out_47),
		.scan_out_48 (n_box_scan_out_48),
		.scan_out_49 (n_box_scan_out_49),
		.scan_out_5 (n_box_scan_out_5),
		.scan_out_50 (n_box_scan_out_50),
		.scan_out_51 (n_box_scan_out_51),
		.scan_out_52 (n_box_scan_out_52),
		.scan_out_53 (n_box_scan_out_53),
		.scan_out_54 (n_box_scan_out_54),
		.scan_out_55 (n_box_scan_out_55),
		.scan_out_56 (n_box_scan_out_56),
		.scan_out_57 (n_box_scan_out_57),
		.scan_out_58 (n_box_scan_out_58),
		.scan_out_59 (n_box_scan_out_59),
		.scan_out_6 (n_box_scan_out_6),
		.scan_out_60 (n_box_scan_out_60),
		.scan_out_61 (n_box_scan_out_61),
		.scan_out_62 (n_box_scan_out_62),
		.scan_out_63 (n_box_scan_out_63),
		.scan_out_64 (n_box_scan_out_64),
		.scan_out_65 (n_box_scan_out_65),
		.scan_out_66 (n_box_scan_out_66),
		.scan_out_67 (n_box_scan_out_67),
		.scan_out_68 (n_box_scan_out_68),
		.scan_out_69 (n_box_scan_out_69),
		.scan_out_7 (n_box_scan_out_7),
		.scan_out_70 (n_box_scan_out_70),
		.scan_out_71 (n_box_scan_out_71),
		.scan_out_72 (n_box_scan_out_72),
		.scan_out_73 (n_box_scan_out_73),
		.scan_out_74 (n_box_scan_out_74),
		.scan_out_75 (n_box_scan_out_75),
		.scan_out_76 (n_box_scan_out_76),
		.scan_out_77 (n_box_scan_out_77),
		.scan_out_78 (n_box_scan_out_78),
		.scan_out_79 (n_box_scan_out_79),
		.scan_out_8 (n_box_scan_out_8),
		.scan_out_80 (n_box_scan_out_80),
		.scan_out_81 (n_box_scan_out_81),
		.scan_out_82 (n_box_scan_out_82),
		.scan_out_83 (n_box_scan_out_83),
		.scan_out_84 (n_box_scan_out_84),
		.scan_out_85 (n_box_scan_out_85),
		.scan_out_86 (n_box_scan_out_86),
		.scan_out_87 (n_box_scan_out_87),
		.scan_out_88 (n_box_scan_out_88),
		.scan_out_89 (n_box_scan_out_89),
		.scan_out_9 (n_box_scan_out_9),
		.scan_out_90 (n_box_scan_out_90),
		.scan_out_91 (n_box_scan_out_91),
		.scan_out_92 (n_box_scan_out_92),
		.scan_out_93 (n_box_scan_out_93),
		.scan_out_94 (n_box_scan_out_94),
		.scan_out_95 (n_box_scan_out_95),
		.scan_out_96 (n_box_scan_out_96),
		.scan_out_97 (n_box_scan_out_97),
		.scan_out_98 (n_box_scan_out_98),
		.scan_out_99 (n_box_scan_out_99),
		.wbr_se (soc_wbr_se),
		.wbr_si (wbr_mid1),
		.wbr_so (wbr_mid2)
	);

	wire n_gfs_scan_en;
	wire n_gfs_scan_in_0;
	wire n_gfs_scan_in_1;
	wire n_gfs_scan_in_10;
	wire n_gfs_scan_in_11;
	wire n_gfs_scan_in_12;
	wire n_gfs_scan_in_13;
	wire n_gfs_scan_in_14;
	wire n_gfs_scan_in_15;
	wire n_gfs_scan_in_16;
	wire n_gfs_scan_in_17;
	wire n_gfs_scan_in_18;
	wire n_gfs_scan_in_19;
	wire n_gfs_scan_in_2;
	wire n_gfs_scan_in_20;
	wire n_gfs_scan_in_21;
	wire n_gfs_scan_in_22;
	wire n_gfs_scan_in_23;
	wire n_gfs_scan_in_24;
	wire n_gfs_scan_in_25;
	wire n_gfs_scan_in_26;
	wire n_gfs_scan_in_27;
	wire n_gfs_scan_in_28;
	wire n_gfs_scan_in_29;
	wire n_gfs_scan_in_3;
	wire n_gfs_scan_in_30;
	wire n_gfs_scan_in_31;
	wire n_gfs_scan_in_32;
	wire n_gfs_scan_in_33;
	wire n_gfs_scan_in_34;
	wire n_gfs_scan_in_35;
	wire n_gfs_scan_in_36;
	wire n_gfs_scan_in_37;
	wire n_gfs_scan_in_38;
	wire n_gfs_scan_in_39;
	wire n_gfs_scan_in_4;
	wire n_gfs_scan_in_40;
	wire n_gfs_scan_in_41;
	wire n_gfs_scan_in_42;
	wire n_gfs_scan_in_43;
	wire n_gfs_scan_in_44;
	wire n_gfs_scan_in_45;
	wire n_gfs_scan_in_46;
	wire n_gfs_scan_in_47;
	wire n_gfs_scan_in_5;
	wire n_gfs_scan_in_6;
	wire n_gfs_scan_in_7;
	wire n_gfs_scan_in_8;
	wire n_gfs_scan_in_9;
	wire n_gfs_scan_out_0;
	wire n_gfs_scan_out_1;
	wire n_gfs_scan_out_10;
	wire n_gfs_scan_out_11;
	wire n_gfs_scan_out_12;
	wire n_gfs_scan_out_13;
	wire n_gfs_scan_out_14;
	wire n_gfs_scan_out_15;
	wire n_gfs_scan_out_16;
	wire n_gfs_scan_out_17;
	wire n_gfs_scan_out_18;
	wire n_gfs_scan_out_19;
	wire n_gfs_scan_out_2;
	wire n_gfs_scan_out_20;
	wire n_gfs_scan_out_21;
	wire n_gfs_scan_out_22;
	wire n_gfs_scan_out_23;
	wire n_gfs_scan_out_24;
	wire n_gfs_scan_out_25;
	wire n_gfs_scan_out_26;
	wire n_gfs_scan_out_27;
	wire n_gfs_scan_out_28;
	wire n_gfs_scan_out_29;
	wire n_gfs_scan_out_3;
	wire n_gfs_scan_out_30;
	wire n_gfs_scan_out_31;
	wire n_gfs_scan_out_32;
	wire n_gfs_scan_out_33;
	wire n_gfs_scan_out_34;
	wire n_gfs_scan_out_35;
	wire n_gfs_scan_out_36;
	wire n_gfs_scan_out_37;
	wire n_gfs_scan_out_38;
	wire n_gfs_scan_out_39;
	wire n_gfs_scan_out_4;
	wire n_gfs_scan_out_40;
	wire n_gfs_scan_out_41;
	wire n_gfs_scan_out_42;
	wire n_gfs_scan_out_43;
	wire n_gfs_scan_out_44;
	wire n_gfs_scan_out_45;
	wire n_gfs_scan_out_46;
	wire n_gfs_scan_out_47;
	wire n_gfs_scan_out_5;
	wire n_gfs_scan_out_6;
	wire n_gfs_scan_out_7;
	wire n_gfs_scan_out_8;
	wire n_gfs_scan_out_9;

	genericfir_small u_genericfir_small (
		.i_ce (i_ce),
		.i_clk (i_clk),
		.i_reset (i_reset),
		.i_sample (boxcar_out[21:14]),
		.i_tap (i_tap),
		.i_tap_wr (i_tap_wr),
		.o_result (o_result),
		.scan_en (n_gfs_scan_en),
		.scan_in_0 (n_gfs_scan_in_0),
		.scan_in_1 (n_gfs_scan_in_1),
		.scan_in_10 (n_gfs_scan_in_10),
		.scan_in_11 (n_gfs_scan_in_11),
		.scan_in_12 (n_gfs_scan_in_12),
		.scan_in_13 (n_gfs_scan_in_13),
		.scan_in_14 (n_gfs_scan_in_14),
		.scan_in_15 (n_gfs_scan_in_15),
		.scan_in_16 (n_gfs_scan_in_16),
		.scan_in_17 (n_gfs_scan_in_17),
		.scan_in_18 (n_gfs_scan_in_18),
		.scan_in_19 (n_gfs_scan_in_19),
		.scan_in_2 (n_gfs_scan_in_2),
		.scan_in_20 (n_gfs_scan_in_20),
		.scan_in_21 (n_gfs_scan_in_21),
		.scan_in_22 (n_gfs_scan_in_22),
		.scan_in_23 (n_gfs_scan_in_23),
		.scan_in_24 (n_gfs_scan_in_24),
		.scan_in_25 (n_gfs_scan_in_25),
		.scan_in_26 (n_gfs_scan_in_26),
		.scan_in_27 (n_gfs_scan_in_27),
		.scan_in_28 (n_gfs_scan_in_28),
		.scan_in_29 (n_gfs_scan_in_29),
		.scan_in_3 (n_gfs_scan_in_3),
		.scan_in_30 (n_gfs_scan_in_30),
		.scan_in_31 (n_gfs_scan_in_31),
		.scan_in_32 (n_gfs_scan_in_32),
		.scan_in_33 (n_gfs_scan_in_33),
		.scan_in_34 (n_gfs_scan_in_34),
		.scan_in_35 (n_gfs_scan_in_35),
		.scan_in_36 (n_gfs_scan_in_36),
		.scan_in_37 (n_gfs_scan_in_37),
		.scan_in_38 (n_gfs_scan_in_38),
		.scan_in_39 (n_gfs_scan_in_39),
		.scan_in_4 (n_gfs_scan_in_4),
		.scan_in_40 (n_gfs_scan_in_40),
		.scan_in_41 (n_gfs_scan_in_41),
		.scan_in_42 (n_gfs_scan_in_42),
		.scan_in_43 (n_gfs_scan_in_43),
		.scan_in_44 (n_gfs_scan_in_44),
		.scan_in_45 (n_gfs_scan_in_45),
		.scan_in_46 (n_gfs_scan_in_46),
		.scan_in_47 (n_gfs_scan_in_47),
		.scan_in_5 (n_gfs_scan_in_5),
		.scan_in_6 (n_gfs_scan_in_6),
		.scan_in_7 (n_gfs_scan_in_7),
		.scan_in_8 (n_gfs_scan_in_8),
		.scan_in_9 (n_gfs_scan_in_9),
		.scan_out_0 (n_gfs_scan_out_0),
		.scan_out_1 (n_gfs_scan_out_1),
		.scan_out_10 (n_gfs_scan_out_10),
		.scan_out_11 (n_gfs_scan_out_11),
		.scan_out_12 (n_gfs_scan_out_12),
		.scan_out_13 (n_gfs_scan_out_13),
		.scan_out_14 (n_gfs_scan_out_14),
		.scan_out_15 (n_gfs_scan_out_15),
		.scan_out_16 (n_gfs_scan_out_16),
		.scan_out_17 (n_gfs_scan_out_17),
		.scan_out_18 (n_gfs_scan_out_18),
		.scan_out_19 (n_gfs_scan_out_19),
		.scan_out_2 (n_gfs_scan_out_2),
		.scan_out_20 (n_gfs_scan_out_20),
		.scan_out_21 (n_gfs_scan_out_21),
		.scan_out_22 (n_gfs_scan_out_22),
		.scan_out_23 (n_gfs_scan_out_23),
		.scan_out_24 (n_gfs_scan_out_24),
		.scan_out_25 (n_gfs_scan_out_25),
		.scan_out_26 (n_gfs_scan_out_26),
		.scan_out_27 (n_gfs_scan_out_27),
		.scan_out_28 (n_gfs_scan_out_28),
		.scan_out_29 (n_gfs_scan_out_29),
		.scan_out_3 (n_gfs_scan_out_3),
		.scan_out_30 (n_gfs_scan_out_30),
		.scan_out_31 (n_gfs_scan_out_31),
		.scan_out_32 (n_gfs_scan_out_32),
		.scan_out_33 (n_gfs_scan_out_33),
		.scan_out_34 (n_gfs_scan_out_34),
		.scan_out_35 (n_gfs_scan_out_35),
		.scan_out_36 (n_gfs_scan_out_36),
		.scan_out_37 (n_gfs_scan_out_37),
		.scan_out_38 (n_gfs_scan_out_38),
		.scan_out_39 (n_gfs_scan_out_39),
		.scan_out_4 (n_gfs_scan_out_4),
		.scan_out_40 (n_gfs_scan_out_40),
		.scan_out_41 (n_gfs_scan_out_41),
		.scan_out_42 (n_gfs_scan_out_42),
		.scan_out_43 (n_gfs_scan_out_43),
		.scan_out_44 (n_gfs_scan_out_44),
		.scan_out_45 (n_gfs_scan_out_45),
		.scan_out_46 (n_gfs_scan_out_46),
		.scan_out_47 (n_gfs_scan_out_47),
		.scan_out_5 (n_gfs_scan_out_5),
		.scan_out_6 (n_gfs_scan_out_6),
		.scan_out_7 (n_gfs_scan_out_7),
		.scan_out_8 (n_gfs_scan_out_8),
		.scan_out_9 (n_gfs_scan_out_9),
		.wbr_se (soc_wbr_se),
		.wbr_si (wbr_mid2),
		.wbr_so (soc_wbr_so)
	);

endmodule
