"""The SDC fragment mbist-insert writes beside the inserted RTL: every clock-
domain crossing it inserted, each into the first flop of a two-flop
synchronizer.

- The chip reset into each shell's reset synchronizer (u_rst_sync), released on
  the memory's clock.
- Each control input of a shell into its synchronizer (u_sync_<port>): from the
  JTAG network's TDRs, or from chip pins.
- With JTAG: each status bit into its READ TDR's synchronizer (pin pi), and the
  chip reset into the control TDRs' clear synchronizer (warptap_chip_reset_sync).

This is the RTL version: the objects are hierarchical pins of the inserted RTL by
instance path ("/" between levels), for whoever synthesizes that RTL keeping its
hierarchy. It says what was inserted; it is not a CDC analysis, and timing
sign-off stays the designer's.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass

from faultflow.mbist.jtag import CHIP_RESET_SYNC, JtagInsertion
from faultflow.mbist.shell import CollarPort

# The READ TDR cell that captures through two TCK flops.
_SYNC_READ_CELL = "bc1_shift_only_sync"


@dataclass(frozen=True)
class Crossing:
    path: tuple[str, ...]  # instance names from the top's down to the synchronizer
    pin: str  # its input the crossing enters through
    what: str


def crossings(
    shells: Sequence[tuple[tuple[str, ...], Sequence[CollarPort]]],
    jtag: JtagInsertion | None,
) -> list[Crossing]:
    """The crossings into each shell (its instance path, as instance names, and
    its ports), then the JTAG network's."""
    found: list[Crossing] = []
    for path, ports in shells:
        found.append(
            Crossing((*path, "u_rst_sync"), "rst_n", "the chip reset, into clk")
        )
        for port in ports:
            if port.kind == "control":
                found.append(
                    Crossing(
                        (*path, f"u_sync_{port.name}"), "d", f"{port.name}, into clk"
                    )
                )
    if jtag is not None:
        for cell, module in sorted(jtag.cells.items()):
            if module == _SYNC_READ_CELL:
                found.append(Crossing((cell,), "pi", "a status bit, into TCK"))
        if CHIP_RESET_SYNC in jtag.cells:
            found.append(
                Crossing((CHIP_RESET_SYNC,), "chip_rst_n", "the chip reset, into TCK")
            )
    return found


def sdc_name(parts: Sequence[str]) -> str:
    """A hierarchical name for get_pins: levels joined with "/", the brackets of
    a generate block's instance name escaped so they match literally."""
    return "/".join(re.sub(r"([\[\]])", r"\\\1", part) for part in parts)


def rtl_sdc(rtl_name: str, found: Sequence[Crossing]) -> str:
    lines = [
        f"# Generated by FaultFlow mbist-insert for {rtl_name}: the clock-domain",
        "# crossings it inserted, each into the first flop of a two-flop synchronizer.",
        "# The pins are hierarchical pins of that RTL; for a synthesized netlist, use",
        "# the SDC written from it. This says what was inserted. It is not a CDC",
        "# analysis, and timing sign-off stays the designer's.",
    ]
    for crossing in found:
        name = sdc_name((*crossing.path, crossing.pin))
        lines += [
            "",
            f"# {crossing.what}",
            f"set_false_path -through [get_pins {{{name}}}]",
        ]
    return "\n".join(lines) + "\n"
