"""The shell mbist-insert puts in place of a memory: the autoMBIST collar, plus
what a collar inside someone else's chip needs around it.

- A reset synchronizer: the collar's reset asserts with the chip reset and
  releases two clk edges after it (u_rst_sync). Its flops stay out of scan: with
  the chip reset held inactive they read 1 two edges into a scan test, and they
  drive the collar's async resets, which a scan shift must never toggle.
- A two-flop synchronizer on every control input (u_sync_<port>), reset by the
  synchronized reset: control comes from another clock domain (JTAG, or pins).
- A two-cycle delay on every done-type status output (u_delay_<port>, a status
  output named *_done): autoMBIST sets the fail flag and enters its done state
  on the same edge, so after the delay the fail flag is final when done rises.

Every other port passes straight through, the functional ones (func_*) too:
the memory's functional path gains no logic but the collar's own mux.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any

SYNC_MODULE = "faultflow_mbist_sync2"
DELAY_MODULE = "faultflow_mbist_delay2"
RESET_SYNC_MODULE = "faultflow_mbist_rst_sync"
LIBRARY_MODULES = (RESET_SYNC_MODULE, SYNC_MODULE, DELAY_MODULE)

LIBRARY_VERILOG = f"""\
// Generated by FaultFlow mbist-insert.

// Asserts with rst_n, releases two clk edges after it.
module {RESET_SYNC_MODULE} (
    input  wire clk,
    input  wire rst_n,
    output wire rst_n_sync
);
    reg [1:0] stages;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) stages <= 2'b00;
        else        stages <= {{stages[0], 1'b1}};
    assign rst_n_sync = stages[1];
endmodule

// Two flops on a signal from another clock domain.
module {SYNC_MODULE} #(parameter integer WIDTH = 1) (
    input  wire             clk,
    input  wire             rst_n,
    input  wire [WIDTH-1:0] d,
    output wire [WIDTH-1:0] q
);
    reg [WIDTH-1:0] first, second;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) begin
            first  <= {{WIDTH{{1'b0}}}};
            second <= {{WIDTH{{1'b0}}}};
        end else begin
            first  <= d;
            second <= first;
        end
    assign q = second;
endmodule

// Two clk cycles of delay, within one clock domain.
module {DELAY_MODULE} #(parameter integer WIDTH = 1) (
    input  wire             clk,
    input  wire             rst_n,
    input  wire [WIDTH-1:0] d,
    output wire [WIDTH-1:0] q
);
    reg [WIDTH-1:0] first, second;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) begin
            first  <= {{WIDTH{{1'b0}}}};
            second <= {{WIDTH{{1'b0}}}};
        end else begin
            first  <= d;
            second <= first;
        end
    assign q = second;
endmodule
"""


class ShellError(ValueError):
    """The collar doesn't have the ports a shell is built around."""


@dataclass(frozen=True)
class CollarPort:
    name: str
    direction: str  # "input" | "output"
    width: int

    @property
    def kind(self) -> str:
        """clock, reset, functional, control (an input from the test access),
        done (a done-type status) or status."""
        if self.name == "clk":
            return "clock"
        if self.name == "rst_n":
            return "reset"
        if self.name.startswith("func_"):
            return "functional"
        if self.direction == "input":
            return "control"
        return "done" if self.name.endswith("_done") else "status"


def collar_ports(module: dict[str, Any]) -> tuple[CollarPort, ...]:
    """The ports of an elaborated collar module (Yosys JSON), in order."""
    ports = []
    for name, port in module.get("ports", {}).items():
        direction = port.get("direction")
        if direction not in ("input", "output"):
            raise ShellError(f"collar port {name!r} is {direction}; only in/out")
        ports.append(CollarPort(name, direction, len(port.get("bits", []))))
    kinds = [p.kind for p in ports]
    for needed in ("clock", "reset"):
        if needed not in kinds:
            raise ShellError(f"the collar has no {needed} port (clk, rst_n)")
    if "control" not in kinds:
        raise ShellError("the collar has no control input (test_mode, bist_start)")
    return tuple(ports)


def _decl(port: CollarPort) -> str:
    kind = "input  wire" if port.direction == "input" else "output wire"
    rng = f" [{port.width - 1}:0]" if port.width > 1 else ""
    return f"    {kind}{rng} {port.name}"


def _wire(name: str, width: int) -> str:
    rng = f" [{width - 1}:0]" if width > 1 else ""
    return f"    wire{rng} {name};"


def shell_verilog(shell: str, collar: str, ports: Sequence[CollarPort]) -> str:
    """The shell module `shell` around an instance u_collar of `collar`, with
    the collar's ports."""
    body: list[str] = [
        "    wire rst_n_sync;",
        f"    {RESET_SYNC_MODULE} u_rst_sync (",
        "        .clk(clk), .rst_n(rst_n), .rst_n_sync(rst_n_sync)",
        "    );",
    ]
    binding: dict[str, str] = {"clk": "clk", "rst_n": "rst_n_sync"}
    for port in ports:
        if port.kind == "control":
            synced = f"synced_{port.name}"
            body += [
                _wire(synced, port.width),
                f"    {SYNC_MODULE} #(.WIDTH({port.width})) u_sync_{port.name} (",
                f"        .clk(clk), .rst_n(rst_n_sync), .d({port.name}), "
                f".q({synced})",
                "    );",
            ]
            binding[port.name] = synced
        elif port.kind == "done":
            raw = f"collar_{port.name}"
            body += [
                _wire(raw, port.width),
                f"    {DELAY_MODULE} #(.WIDTH({port.width})) u_delay_{port.name} (",
                f"        .clk(clk), .rst_n(rst_n_sync), .d({raw}), .q({port.name})",
                "    );",
            ]
            binding[port.name] = raw
        else:
            binding.setdefault(port.name, port.name)
    connections = ",\n".join(f"        .{p.name}({binding[p.name]})" for p in ports)
    return "\n".join(
        [
            "// Generated by FaultFlow mbist-insert: the autoMBIST collar "
            f"{collar} with its reset",
            "// synchronized, its control inputs synchronized to clk and its done "
            "outputs delayed.",
            f"module {shell} (",
            ",\n".join(_decl(p) for p in ports),
            ");",
            *body,
            f"    {collar} u_collar (",
            connections,
            "    );",
            "endmodule",
            "",
        ]
    )
